### ISSUE TITLE
Roadmap to v1.0

### ISSUE THREAD

**Issue by hhhapz** [minekube/gate#1]
What are the features that need to be implemented on this project to be a mature project?

**Comment by robinbraemer** [comment]
The roadmap to make Gate mature is:
- being used in production
- extend the command system (tab completion and so on, refer to mojang/brigadier repo)
- bungeecord's plugin channels (to support existing spigot plugins that communicate with the proxy)
- take commands from the console
- being able to reload the config
- further improve the existing algorithm for redirecting players to available servers (match protocol versions, mark unresponsive servers, don't retry moving a player to previous failed connections) and add API to add and remove `try`/`fallback` servers.
- a documentation website explaining configuration, architecture and code examples for customizing Gate
- add APIs for more player interaction -> boss bar, player tab list, action bar, maybe even scoreboards
- add more plugin support with script languages: lua and tengo (this is for the general folks that just want to get startet quick and easy)

We are yet seeing great stability but we should wait for the v1.0 announcement until the Minekube network has been released and is successfully using Gate in production.
Gate is used at Minekube (which is in closed beta rn) for just a couple of days from now and will get more and more maturity and features as needed and developed.

**Comment by Hamzantal** [comment]
Cool! Let me know what specifically to work on, i'd appreciate some CONTRIBUTING.md as it would help out myself as well as other future devs :)

**Comment by robinbraemer** [comment]
Great, you could pick anything from the list if you’re convinced you can implement it.
How about the “// TODO support bungeecord plugin channels” todo?

**Comment by robinbraemer** [comment]
@hhhapz bungee channels have been added, as you asked for something to work on and not responded, you could add console input support (via command manager and adding a console interface implementing command source)

**Comment by robinbraemer** [comment]
Moved as [v1.0.0 milestone](https://github.com/minekube/gate/milestone/1)!
