### ISSUE TITLE
older ver. server+viaversion+newer client: Connected but map not loading

### ISSUE THREAD

**Issue by rafalohaki** [minekube/gate#112]
Map not loading and cant write in chat too.
1.8 server FlamePaper
tested on 1.19.2 client and 1.8.9 client
https://mclo.gs/k6lx4gG

**Comment by robinbraemer** [comment]
Do you have any plugins on the server?

**Comment by rafalohaki** [comment]
spark, protocollib, viaversion

**Comment by robinbraemer** [comment]
Does it work when you use normal Paper?

**Comment by rafalohaki** [comment]
the same. 
server 1.18.2 puprur with viaversion
using client 1.19.2
https://mclo.gs/GYfoicd

**Comment by rafalohaki** [comment]
![image](https://user-images.githubusercontent.com/20607107/208269639-813f409c-dd4a-4b6e-8b9c-1d2aab5ee932.png)

**Comment by robinbraemer** [comment]
What happens when you use Velocity or Bungeecord instead of Gate?

**Comment by rafalohaki** [comment]
> What happens when you use Velocity or Bungeecord instead of Gate?

its working with velocity. on 1.8 server and 1.18 server

**Comment by robinbraemer** [comment]
I'm on it to fix it

**Comment by robinbraemer** [comment]
Fixed by 5d2c0ce153cbf886681526a27944244dc2ce107d
`go get go.minekube.com/gate@latest`
