### ISSUE TITLE
Support for arm in docker image

### ISSUE THREAD

**Issue by viasnake** [minekube/gate#116]
The current Docker image does not work on arm.
Some servers may use arm, so it may be a good idea to support it.

I have rebuilt it with ARM, and it seems to work fine.
So I don't think it is necessary to change the code.
If you want to test the arm build, check [my repository](https://github.com/mcplaynetwork/gate-arm/pkgs/container/gate-arm).

**Comment by robinbraemer** [comment]
Thanks for your report! I'll add more architectures since Gate should be accessible to everyone.

**Comment by robinbraemer** [comment]
Docker will now pull the right image for your architecture for the official Gate image `ghcr.io/minekube/gate:latest`.
