### ISSUE TITLE
[Feature Request] Gate Lite mode fallback motd for offline backends

### ISSUE THREAD

**Issue by SnyderWillCode** [minekube/gate#157]
Can you guys please add a feature, if gate-lite finds a server that is offline it will send an Offline MOTD placeholder telling why the server is offline or where it is hosted. "Server is down for a little", "This server is hosted on Kholex.tech" , it is customizable the conifg.yml. Hopefully your are able to add this.

**Comment by robinbraemer** [comment]
I hope you can find an experiences Gopher to add this feature to Gate Lite.  I don't have the time myself currently.
