### ISSUE TITLE
Kubernetes Helm chart

### ISSUE THREAD

**Issue by clrxbl** [minekube/gate#188]
There is an example Kustomize deployment provided. It'd be nice to expand this to Helm.

**Comment by robinbraemer** [comment]
I don't like Helm to the extent that I wouldn't find enough joy in maintaining a Helm repo for Gate. 
[kpt](https://kpt.dev/) and [Kustomize](https://kustomize.io/) are awesome and well built into k8s.
You are free to maintain a Helm package for Gate and contribute if it's great, though I don't have the time.
