### ISSUE TITLE
Stuck on "Joining world..." on 1.19.4

### ISSUE THREAD

**Issue by CoasterFreakDE** [minekube/gate#190]
When trying to join a 1.19.4 server with gate as a proxy, the client fails to join the world.

The client is stuck at the Joining world screen.
There is no timeout, as the client is successfully connected to the server.
Other users (on lower versions) can see and interact with this user.

Tried it on a production server and a fresh new installed test server. Both with legacy and velocity protocol. (paper-1.19.4#477)

It seems like there is a packet missing, that tells the client it is connected and should load the terrain.

![joiningworld](https://user-images.githubusercontent.com/28011628/228208020-175928df-aa36-489b-aa08-f6fe00341029.png)

**Comment by robinbraemer** [comment]
Thanks for the report, it's fixed!
