### ISSUE TITLE
Configurable authentication server URL

### ISSUE THREAD

**Issue by Gk0Wk** [minekube/gate#22]
The official Minecraft authentication URL is `https://sessionserver.mojang.com/session/minecraft/xxx`. However, in some cases, the server can use its own authentication service (implementing Mojang's authentication API).

For example: `https://my.authentication.site/api/xxx`.

I know of some proven solutions to implement this authentication service: [authlib-injector](https://github.com/yushijinhun/authlib-injector/blob/develop/README.en.md) works on servers and clients, and [Blessing-Skin](https://github.com/bs-community/blessing-skin-server) is a web service.

---

By making the variable `mojangURL` in `gate/pkg/edition/java/auth/authenticator.go` configurable,  Gate will be able to implement third-party authentication.

This can be cool :)

**Comment by robinbraemer** [comment]
Thank you for your feature request!

Even though one could implement the Authenticator interface and pass to create a proxy instance https://github.com/minekube/gate/blob/8dac29db675713c10afbb8304690f3dc13ce904a/pkg/edition/java/proxy/proxy.go#L74 I see the convenience in your suggestion.

I've added support for it in 3d2a66684b5d4c0faa24f598c908498c795e4e03.
