### ISSUE TITLE
feat: [Lite mode] - Motd caching per hostname

### ISSUE THREAD

**Issue by julian-siebert** [minekube/gate#247]
Imagine having a route to a Velocity instance with Gate Lite available with *.example.com.
The Gate Lite config would look just like this:

lite:
    enabled: true
    routes:
      - host: '*.example.com'
        backend: 0.0.0.0:25566
        proxyProtocol: true
        cachePingTTL: 3m

Here we have ping caching set to 3 minutes, which is what we want.

Let's imagine the Velocity wants two send different motds depending on the hostname used by the player.
For example pinging with motd1.example.com should return a different motd than with motd2.example.com, which is handled with a velocity plugin or something else.

The issue is, that the ping cache doesn't care about the hostname, which is kinda unfortunate.

It would be great if the cache would remember which hostname has been used.
I would suggest adding another option for disabling/enabling such behaviour.

**Comment by robinbraemer** [comment]
Thanks for the feature request! I’ll prioritize it as low since workaround would be to simply disable caching. This feature will likely get added though!

**Comment by julian-siebert** [comment]
nice, thank you
