### ISSUE TITLE
Send Player a packet  

### ISSUE THREAD

**Issue by AaronNBrock** [minekube/gate#27]
When listening to events, it would be useful to send have access to the `*minecraftConn` object to send arbitrary packets. 

To allow for this, I propose exporting `connectedPlayer`  to `ConnectedPlayer` so someone writing a plugin can cast:

```golang
player, ok := e.Player().(*proxy.ConnectedPlayer)
if ok {
	player.WritePacket( /* some packet */ )
}
```

I can make a PR if this looks good.

**Comment by robinbraemer** [comment]
This struct is for reasons not exportet and kept _internal_ for now.
How about adding `WritePacket` to the `Player` interface or simply doing this?:
```go
i, ok := e.Player().(interface {
   WritePacket(proto.Packet) error
})
```

**Comment by AaronNBrock** [comment]
Either of those solutions work for me!  (if it wasn't obvious I'm not usually a Go dev 😉)
