### ISSUE TITLE
Puffer Panel template

### ISSUE THREAD

**Issue by A53o** [minekube/gate#321]
If there isn't already one it would be great if you guys could create a template for gate on puffer panel. [Templates page](https://github.com/PufferPanel/templates)

**Comment by robinbraemer** [comment]
Hey, if you are familiar with templates, feel free to share or ask in our discord if there is a dev to do it.

**Comment by A53o** [comment]
I'm not very sure how it all works but it has info on adding templates [here](https://github.com/PufferPanel/templates)

**Comment by dilllxd** [comment]
Hey @A53o! If you're still interested in a PufferPanel template, please message me on Discord at the username Dilll. I'm in the Minekube server.

I have a potential template that _might_ work, but I don't have a PufferPanel install to test it on.

**Comment by A53o** [comment]
Yeah I saw the thread it's literally what I've been looking for this entire time thanks bro I'll do some testing and let you know if there's any problems

**Comment by robinbraemer** [comment]
Solved in [Discord post](https://discord.com/channels/633708750032863232/1235996906665279538).

@dilllxd you're a genius, let's add it to https://github.com/minekube/awesome!
