### ISSUE TITLE
How to access Rcon-protocol or manage its ports

### ISSUE THREAD

**Issue by nglmercer** [minekube/gate#397]
Rcon-protocol is very useful to manage a server through another application or use it as an api.
The problem is that you have to enable an extra port on some hostings, by default on localhost it is not necessary because it is enabled or accessible.
How could I make it work or configure it since I could not connect or allow the connection to the Rcon-port

**Comment by robinbraemer** [comment]
Hey, I'm trying to understand. What would you like to control in Gate over RCON?

**Comment by nglmercer** [comment]
I would like to send commands so I can get information or execute functions

**Comment by robinbraemer** [comment]
Would [customizing](https://github.com/minekube/gate-plugin-template) Gate work for you? You could add your own rcon or any other communication protocol to run commands.

**Comment by nglmercer** [comment]
Sure, something like that would be great.
