### ISSUE TITLE
Bug: Double Slash or More Commands Not Being Parsed Properly

### ISSUE THREAD

**Issue by dilllxd** [minekube/gate#414]
Thanks to some people over on Discord it was noticed that Gate is not properly handling commands that have more than one slash. This is seemingly related to https://github.com/minekube/gate/blob/9a51e7231917a3b4e4c47b95fdb44b683a0ee37d/pkg/edition/java/proxy/handle_cmd.go#L46 I'm new to Go and Gate overall still so I'm not sure how changing this affects anything else however changing this line to 
`cmd := message` solves the problem from what I can tell. Gate commands like /send still work as well as //wand or /help. Please feel free to test more though before just pushing this change as I know really nothing about how Gate's command handling works and I haven't really tested this thoroughly enough imo.

![8z9hpq7g](https://github.com/user-attachments/assets/ba4c7207-28ac-466e-8cf0-0e1e4926b738)

**Comment by robinbraemer** [comment]
Thanks, that has fixed it in my testing as well.
