### ISSUE TITLE
Minecraft 1.18 support

### ISSUE THREAD

**Issue by paralin** [minekube/gate#49]
The protocol changed (significantly?) in 1.18.

Some other proxies have updated already:

 - https://github.com/GeyserMC/Geyser
 - https://github.com/GeyserMC/MCProtocolLib/commits/master

... need to update this too. will have a look at doing it

**Comment by robinbraemer** [comment]
I'll update Gate to 1.18 when I find the time. I usually look at what Velocity has changed as they are quite fast.
The updates that need to be implemented in Gate are will be this changelog: https://github.com/PaperMC/Velocity/compare/311133a4d3342e81ac99fafd8955e1641524d33e...dev/3.0.0

**Comment by robinbraemer** [comment]
1.18 support added in https://github.com/minekube/gate/commit/d1b15b0b033325b5786ed536458fa3cbb5536d8d
