### ISSUE TITLE
Switching worlds does not refresh everything in chunks

### ISSUE THREAD

**Issue by QuickWrite** [minekube/gate#50]
## What is the bug:
When the player is switching between different servers some chunk errors (just Client Side) can happen:
<img src="https://user-images.githubusercontent.com/54590845/146689196-c3a6128a-2a5e-4490-be1f-c26488eaf02a.png" height="350" alt="Wrong chunks in Minecraft" title="These chunks come from the other world" />
When the player is coming near the chunks these will disappear, but it is still a little bit annoying.

These are the chunks that are from the previous world the player was in.

This is especially the case with entities as they are just standing there as if nothing happened and the player cannot interact with them:
<img src="https://user-images.githubusercontent.com/54590845/146689223-ffe03640-381a-4ba6-9a02-a9625420ba71.png" height="350" alt="Animals in the air in Minecraft" title="These animals come from the other world" />

## Setup:
It was not tested in other setups so here is the setup:

It is the `examples/simple-network` but with the modification that the servers are `1.17.1 paper servers` and not `1.16 paper server`.

## Tested versions:
- **Server**:
  - Two `paper-1.17.1-333` servers
  - `gate_0.14.1_windows_amd64.exe`
- **Client**:
  - Optifine 1.17.1
  - Minecraft 1.17.1 (So that nobody can say that it is an Optifine Bug)

This was tested on Windows.

## Footnote
I hope this helps a little bit and if I have overlooked another issue with the same topic you can close it 😄.

**Comment by robinbraemer** [comment]
fixed in https://github.com/minekube/gate/commit/0767fc5ee08bafa9132ac0bb9066976edac394a6
