### ISSUE TITLE
Question about command aliases.

### ISSUE THREAD

**Issue by luiz-otavio** [minekube/gate#69]
I tried to make a command with alot of aliases such as:

1. `/hub`
2. `/l`
3. `/lobby`

But, it looks like there's no way to introduce aliases in one command. (Maybe I didn't understand in docs)
How could I do this?

**Comment by robinbraemer** [comment]
Aliases are supportet!

Use Redirect, passing in the Node that has your command logic. 

https://github.com/minekube/brigodier/blob/0327262d340c4367ff9bce7e4f4193404aec0ebc/builder.go#L23 

Ping me if you need a code example. ;)

**Comment by robinbraemer** [comment]
```go

cmd := brigodier.Literal("glist")
	
p.command.Register(cmd)
p.command.Register(aliasCmd("list", cmd))

func aliasCmd(name string, cmd brigodier.LiteralNodeBuilder) brigodier.LiteralNodeBuilder {
	return brigodier.Literal(name).Redirect(cmd.BuildLiteral())
}

```
