### ISSUE TITLE
Support for scripting languages as plugins

### ISSUE THREAD

**Issue by robinbraemer** [minekube/gate#9]
### This issue is there to discuss the support for scripting languages in Gate.

To simplify and accelerate customization Gate should add support for popular scripting languages like:
- [Lua](https://github.com/yuin/gopher-lua) (with [this lib](https://github.com/layeh/gopher-luar))
- [Tengo](https://github.com/d5/tengo)

Which language should we target first?

Specifically Lua has being requested under [Gate's reddit post](https://www.reddit.com/r/golang/comments/ideg2v/gate_the_extensible_minecraft_proxy_written_in_go/g29bpex?utm_source=share&utm_medium=web2x&context=3).
Please up-vote this issue whether this scripting should be added and/or comment some thoughts on this.

**Comment by legendary-cookie** [comment]
Any updates on this?

**Comment by robinbraemer** [comment]
None. Do you want to use a script language?

**Comment by legendary-cookie** [comment]
I'd find it useful if some kind of plugin system would be implemented, that could load both scripting languages and also go modules.

**Comment by legendary-cookie** [comment]
Scripting languages could be used to create a quick plugin that sends custom messages etc.

**Comment by legendary-cookie** [comment]
If wanted, I could implement some support, if you give me some directions!

**Comment by robinbraemer** [comment]
> I'd find it useful if some kind of plugin system would be implemented, that could load both scripting languages and also go modules.

Do the examples help to understand a bit of Go for beginners? Go is simple to read and write. 

Do you have specific script language in mind?

**Comment by legendary-cookie** [comment]
If beginners had previous experiences with another simple language, they should easily be able to use go, I think

As for the scripting language, I thought of Lua

**Comment by robinbraemer** [comment]
> If wanted, I could implement some support, if you give me some directions!

@legendary-cookie I'm open to adding a Lua plugin system to Gate.
- [Lua](https://github.com/yuin/gopher-lua) (with [this lib](https://github.com/layeh/gopher-luar)?)
- How to design it is up to you. I have not thought of it yet.

**Comment by legendary-cookie** [comment]
I'll look a bit into the code to get a better understanding overall, then I'll think of the design! Also the lib looks pretty good.

**Comment by robinbraemer** [comment]
Awesome

**Comment by Dawsson** [comment]
TS could be cool to use instead of lua, maybe even Java/kt?

**Comment by NullyIsHere** [comment]
This seems abandoned except for someone commenting 7h ago, i would love Python,

**Comment by robinbraemer** [comment]
Would be great if people just 👍 this feature request.
We have developers that would pick this up.

**Comment by NullyIsHere** [comment]
How do we do that?

**Comment by robinbraemer** [comment]
It's finally here, please checkout https://gate.minekube.com/developers/api/!
