### ISSUE TITLE
Add proxy protocol support

### ISSUE THREAD

**Issue by robinbraemer** [minekube/gate#95]
If you have Gate behind a HAProxy or other kind of TCP pass-through proxy with the "proxy procotol" the real player IP would be preserved.

**Comment by samuxita** [comment]
Or bugeecord behind gate

**Comment by robinbraemer** [comment]
> Or bungeecord behind gate

Normally this setting would make Gate to only accept proxyprotocol connections (X -> Gate), but NOT use proxyprotocol for forwarding connection to backend servers (Gate -> Spigot).

Do you need Gate to also use proxyprotocol for the backend server connections, to support your Gate->Bungee setup with bungeecord‘s proxy_protocol setting?

**Comment by samuxita** [comment]
i'm currently using proxy protocol on infrared -> Bungee -> Spigots, i want gate because i tried and is better

**Comment by robinbraemer** [comment]
I'll add proxy protocol support. This goes for incoming connections to Gate, not for connections between Gate and another backend server/proxy.
