### ISSUE TITLE
Add bot filters and more firewall features

### ISSUE THREAD

**Issue by HAMMERxPL** [minekube/gate#96]
I believe that Gate would win with every possible proxy, but it needs some features against attacks, there are couple projects like:
https://github.com/Leymooo/BungeeCord
https://github.com/Elytrium/LimboFilter
which creates feature like falling check - after joining it checks if the player falls/sends movement packets - if not, they are bot and they get kicked.
We noticed that Gate has some CPU spikes under the attack, it could be benchmarked and maybe better structured or it would needs some debug for bad packets or similar things.
Keep up the good job! ❤️

**Comment by samuxita** [comment]
amazing features, i have problem with bot attacks. I get bypassed with all plugins.

**Comment by robinbraemer** [comment]
Taking notes here. As part of the mitigation, we could check if the IP has a fraudulent history by using some of the available API services, e.g.: [this one](https://www.ipqualityscore.com/free-ip-lookup-proxy-vpn-test/lookup/2.42.103.109).

**Comment by samuxita** [comment]
> Taking notes here. As part of the mitigation, we could check if the a client IP has a fraudulent history by using some of the available API services, e.g.: [this one](https://www.ipqualityscore.com/free-ip-lookup-proxy-vpn-test/lookup/2.42.103.109).

Not bad but the problem this api is limited to 5k lookups and only upgrade to 50k it cost 499$.

**Comment by robinbraemer** [comment]
Checkout the Gate Lite mode in combination with OVH DDoS protection.
https://gate.minekube.com/guide/security.html#ddos-protecting-your-minecraft-server

#113

**Comment by robinbraemer** [comment]
I am archiving this inactive request for now.
