### ISSUE TITLE
feat: Add BungeeGuard Compatible mode

### ISSUE THREAD

**Issue by kubo6472** [minekube/gate#97]
Like Velocity 3.x, add mode where it will still support 1.7-1.19.x but use the token for something like BungeeGuard.

**Comment by robinbraemer** [comment]
Are you using BungeeGuard?

**Comment by kubo6472** [comment]
Yes, I was using it with velocity. Wanted to do some testing with gate. As velocity has almost, if not larger memory consumption than a full minecraft server. Truth be told, I'm "hosting" an auth server directly from proxy, using LimboAPI velocity plugin, but still, I tried it without all of that and it still has enormous memory footprint. With versions below 1.13.x I will have to use something like bungeeguard instead of the modern velocity style forwarding.

**Comment by robinbraemer** [comment]
added by #382
